function TS = standardizeLipdNomenclatureTS(TS)


badnames = {'pub1_authors','pub2_authors','pub3_authors','pub4_authors',...
    'pub5_authors','pub6_authors','pub7_authors','pub8_authors','pub9_authors',...
    'dataPub1_authors','dataPub2_authors','dataPub3_authors',...
  'pub1_pubYear','pub2_pubYear','pub3_pubYear','pub4_pubYear',...
    'pub5_pubYear','pub6_pubYear','pub7_pubYear','pub8_pubYear','pub9_pubYear',...
    'dataPub1_pubYear','dataPub2_pubYear','dataPub3_pubYear',...
    'pub1_Year','pub2_Year','pub3_Year','pub4_Year',...
    'pub5_Year','pub6_Year','pub7_Year','pub8_Year','pub9_Year'};

goodnames = {'pub1_author','pub2_author','pub3_author','pub4_author',...
    'pub5_author','pub6_author','pub7_author','pub8_author','pub9_author',...
    'dataPub1_author','dataPub2_author','dataPub3_author',...
  'pub1_year','pub2_year','pub3_year','pub4_year',...
    'pub5_year','pub6_year','pub7_year','pub8_year','pub9_year',...
    'dataPub1_year','dataPub2_year','dataPub3_year',...
      'pub1_year','pub2_year','pub3_year','pub4_year',...
    'pub5_year','pub6_year','pub7_year','pub8_year','pub9_year'};


for i = 1:length(badnames)
    if isfield(TS,badnames{i}) & ~isfield(TS,goodnames{i})
        [TS.(goodnames{i})] = TS.(badnames{i});
    elseif isfield(TS,badnames{i}) & ~isfield(TS,goodnames{i})
        TS = mergeTSfields(TS,goodnames{i},badnames{i});
    end
end

TS = rmfieldsoft(TS,badnames);
TS = structord(TS);